[workspace]

resolver = "2"
members = [
    "crates/dominator-css-bindgen",
    "crates/tests/dominator-css-bindgen-test"
]

[workspace.dependencies]
cssparser = "0.34.0"
dominator = "^0.5.35"
nom = "7.1.3"
once_cell = "^1.19.0"
thiserror = "1.0.61"

