[package]
name = "dwind-build"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/JedimEmO/dwind"
repository = "https://github.com/JedimEmO/dwind"
license-file = "LICENSE"
keywords = ["web", "wasm", "css", "style"]

[dependencies]

serde.workspace = true
serde_json.workspace = true