[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[dominator-cssqwdqwd-bindgen-test-ui.build]
target = "wasm32-unknown-unknown"
