[package]
name = "example-html-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prettyplease.workspace = true
syn.workspace = true
syntect.workspace = true
quote.workspace = true
proc-macro2.workspace = true
